/**
 * Sequel generation prompts (V7 §4, §13.3).
 *
 * CORE AIFLEX DIFFERENTIATOR: a sequel can be generated by ANY subscriber,
 * even if the parent film is not theirs, provided `allowSequels = true` on
 * the parent. The prompt must carry enough parent context (characters,
 * last event, genre, tone) to guarantee narrative and visual continuity.
 *
 * These prompts extend `CONCEPT_INSTRUCTIONS` / `SCENARIO_INSTRUCTIONS` from
 * lib/prompts.ts by prepending parent context. Re-use the 3-step pipeline
 * (concept → scenario → scenes) of the standard flow.
 */

export interface SequelParentContext {
  title: string;
  synopsis: string;
  genre: string;
  tone: string;
  /** Physical description of main characters, extracted from parent scenes. */
  characters: string;
  /** Final dramatic event of the parent film — where the sequel must begin. */
  lastEvent: string;
  /** Optional: visual style / palette reference to preserve cohesion. */
  visualStyle?: string;
}

const CONTINUITY_RULES = `
RÈGLES DE CONTINUITÉ — OBLIGATOIRES :
- Les personnages principaux gardent la MÊME apparence physique que dans le film original (même âge visuel, même vêtements clés, mêmes traits).
- Le ton et l'atmosphère correspondent au film original.
- La suite commence exactement là où le film original s'est terminé (ou après une ellipse justifiée narrativement).
- La suite est autonome : un spectateur qui n'a pas vu le film original doit pouvoir suivre.
- Pas de rétrocontinuité : ne contredis pas les événements du film original.
- Évolution obligatoire : les personnages doivent avoir changé, pas être figés.
`;

function parentContextBlock(parent: SequelParentContext): string {
  return `
CONTEXTE DU FILM PARENT — "${parent.title}" :
- Synopsis : ${parent.synopsis}
- Genre : ${parent.genre}
- Ton : ${parent.tone}
- Personnages principaux : ${parent.characters}
- Dernier événement connu : ${parent.lastEvent}
${parent.visualStyle ? `- Style visuel : ${parent.visualStyle}` : ""}
`.trim();
}

/**
 * Extended concept step for a sequel. Reuses the standard CONCEPT_INSTRUCTIONS
 * format but prepends parent context + continuity rules.
 */
export function buildSequelConceptInstructions(
  parent: SequelParentContext
): string {
  return `Tu écris la SUITE officielle de "${parent.title}" pour AiFlex.

${parentContextBlock(parent)}
${CONTINUITY_RULES}

Enrichis l'idée de l'utilisateur en un concept narratif qui prolonge l'histoire parent.

Retourne un JSON avec EXACTEMENT cette structure :
{
  "title": "titre de la suite (peut contenir un sous-titre, ex: 'Les Ombres de [Lieu]')",
  "logline": "une phrase qui résume le nouveau conflit, en tenant compte de la fin du film parent",
  "synopsis": "résumé de 150-220 mots, en 2-3 paragraphes. Le premier paragraphe DOIT faire le pont avec la fin du film parent.",
  "themes": ["thème1", "thème2", "thème3"],
  "tone": "doit correspondre au ton du film parent",
  "universe": "description visuelle et sensorielle cohérente avec le parent",
  "characters": [
    {
      "name": "nom (reprendre les noms existants du parent quand approprié)",
      "role": "protagoniste | antagoniste | mentor | allié | pivot",
      "description": "physique et mental. Pour les personnages récurrents : MÊME description physique que dans le parent + évolution mentale justifiée par ce qu'il a vécu.",
      "arc": "nouvelle transformation pour ce film",
      "returning": true
    }
  ],
  "targetAudience": "audience visée",
  "parentFilmId": "à remplir côté serveur"
}

Crée 3-5 personnages. AU MOINS UN doit être un personnage récurrent du film parent (\`returning: true\`).`;
}

/**
 * Sequel-specific scenes step: emphasize that the first scene must bridge
 * from the parent film's final beat. Otherwise the standard SCENES_INSTRUCTIONS
 * rules apply.
 */
export function buildSequelScenesInstructions(
  parent: SequelParentContext
): string {
  return `À partir du scénario de la suite de "${parent.title}", découpe l'histoire en scènes filmables.

${parentContextBlock(parent)}

CONTRAINTES VISUELLES DE CONTINUITÉ :
- Pour tout personnage récurrent, chaque \`visualPrompt\` DOIT répéter la description physique (mêmes vêtements clés, mêmes traits, même coiffure) — les modèles text-to-video oublient vite.
- La première scène doit visuellement rappeler la dernière scène du parent (même lieu, ou plan de raccord).
- Palette et grain de lumière cohérents avec le parent.

Retourne un JSON avec EXACTEMENT cette structure :
{
  "scenes": [
    {
      "index": 0,
      "title": "titre court",
      "location": "lieu précis",
      "timeOfDay": "matin | midi | après-midi | crépuscule | nuit | aube",
      "characters": ["nom1"],
      "action": "description de l'action + sous-texte en 2-4 phrases",
      "dialogue": "'NOM : réplique.'",
      "mood": "ambiance en 2-4 mots",
      "visualPrompt": "prompt en ANGLAIS ultra descriptif. Répéter la description physique des personnages récurrents.",
      "durationSec": 8,
      "bridgesFromParent": true
    }
  ]
}

Règles :
- Entre 8 et 14 scènes pour un court, 12-20 pour un long.
- La scène d'index 0 a \`bridgesFromParent: true\` et fait le raccord avec la fin du parent.
- durationSec entre 5 et 10 secondes.`;
}

/**
 * Extract a serializable parent context from a Project row's stored scenes.
 * `scenes` is expected to be the JSON output of SCENES_INSTRUCTIONS.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function extractParentContext(project: any): SequelParentContext {
  const scenes = Array.isArray(project?.scenes) ? project.scenes : [];
  const lastScene = scenes[scenes.length - 1];

  // Extract character descriptions from the first scene's visualPrompt
  // (which by our SCENES_INSTRUCTIONS rule carries full physical descriptions).
  const firstScenePrompt: string = scenes[0]?.visualPrompt ?? "";
  const characterNames: string[] = Array.from(
    new Set(
      scenes.flatMap((s: { characters?: string[] }) => s.characters ?? [])
    )
  );

  const characters =
    characterNames.length > 0
      ? `${characterNames.join(", ")}. Descriptions physiques (extraites du film parent) : ${firstScenePrompt.slice(0, 800)}`
      : firstScenePrompt.slice(0, 800) || "voir scénario parent";

  const lastEvent =
    (lastScene?.action as string) ||
    (lastScene?.dialogue as string) ||
    "fin du film parent";

  return {
    title: project?.title || project?.seriesTitle || "Film sans titre",
    synopsis: project?.synopsis || project?.concept?.synopsis || "",
    genre: project?.genre || project?.concept?.genre || "drame",
    tone: project?.tone || project?.concept?.tone || "cinématographique",
    characters,
    lastEvent,
    visualStyle: scenes[0]?.mood,
  };
}
