"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

interface PayoutRow {
  id: string;
  month: string;
  projectId: string | null;
  netAmount: number;
  payoutType: "primary" | "royalty" | "collab" | "bundle";
}

interface StatusPayload {
  payouts: PayoutRow[];
}

interface Props {
  /** Months back to consider. Default 12. */
  months?: number;
}

/**
 * Royalty-focused widget (V8 §A4).
 *
 * Surfaces the income generated by sequels of films you originally
 * created. Helps creators decide whether `allowSequels` is paying off,
 * and reinforces the unique AIflex value prop.
 *
 * Reuses `/api/stripe/connect/status`, filters `payoutType === "royalty"`.
 */
export default function RoyaltyDashboard({ months = 12 }: Props) {
  const [data, setData] = useState<StatusPayload | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetch("/api/stripe/connect/status", { cache: "no-store" })
      .then((r) => (r.ok ? r.json() : Promise.reject()))
      .then((j: StatusPayload) => {
        if (!cancelled) setData(j);
      })
      .catch(() => {
        if (!cancelled) setData({ payouts: [] });
      });
    return () => {
      cancelled = true;
    };
  }, []);

  if (!data) {
    return (
      <Card>
        <Header />
        <div className="h-12 w-32 animate-pulse rounded bg-flex-card" />
      </Card>
    );
  }

  // Filter royalty rows in the requested window
  const cutoff = monthsAgo(months);
  const royalties = data.payouts.filter(
    (p) => p.payoutType === "royalty" && p.month >= cutoff
  );
  const total = royalties.reduce((acc, p) => acc + p.netAmount, 0);

  // Group by parent film
  const byFilm = new Map<string, number>();
  for (const r of royalties) {
    if (!r.projectId) continue;
    byFilm.set(r.projectId, (byFilm.get(r.projectId) ?? 0) + r.netAmount);
  }
  const topFilms = [...byFilm.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5);

  return (
    <Card>
      <Header />
      <div className="mt-1 font-display text-3xl font-bold text-purple-400">
        ${(total / 100).toFixed(2)}
      </div>
      <p className="mt-1 text-xs text-flex-muted">
        Sur les {months} derniers mois — vues qualifiées des suites de tes films.
      </p>

      {topFilms.length > 0 ? (
        <ul className="mt-4 space-y-1.5 text-sm">
          {topFilms.map(([filmId, amount]) => (
            <li
              key={filmId}
              className="flex items-center justify-between gap-3 rounded-lg bg-flex-card px-3 py-1.5"
            >
              <Link
                href={`/watch/${filmId}`}
                className="truncate text-flex-text hover:text-flex-accent"
              >
                /watch/{filmId}
              </Link>
              <span className="font-medium text-purple-400">
                ${(amount / 100).toFixed(2)}
              </span>
            </li>
          ))}
        </ul>
      ) : (
        <p className="mt-4 text-xs text-flex-muted">
          Aucune royalty pour l&apos;instant. Active{" "}
          <code className="rounded bg-flex-card px-1.5 py-0.5">allowSequels</code>{" "}
          sur tes films pour en générer.
        </p>
      )}

      <Link
        href="/dashboard/payouts"
        className="mt-4 inline-block text-xs text-flex-accent hover:underline"
      >
        Voir tous les versements →
      </Link>
    </Card>
  );
}

function Card({ children }: { children: React.ReactNode }) {
  return (
    <section className="rounded-3xl border border-flex-border bg-flex-panel p-6 shadow-cinema">
      {children}
    </section>
  );
}

function Header() {
  return (
    <div className="flex items-baseline justify-between">
      <div className="text-xs font-semibold uppercase tracking-wider text-flex-muted">
        Royalties suites
      </div>
      <span className="rounded-full bg-purple-500/10 px-2 py-0.5 text-[10px] font-medium uppercase tracking-wider text-purple-400">
        ↺ univers étendu
      </span>
    </div>
  );
}

function monthsAgo(n: number): string {
  const d = new Date();
  d.setUTCMonth(d.getUTCMonth() - n);
  return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, "0")}`;
}
