import "server-only";
import { promises as fs } from "node:fs";
import path from "node:path";
import os from "node:os";
import { spawn } from "node:child_process";

/**
 * Visible + invisible AI watermarking (V8 §19.2, §19.3).
 *
 * The EU AI Act (article 50, enforcement August 2026) and California SB-942
 * require every publicly-distributed AI-generated video to carry a visible
 * notice that it was generated by AI. AIflex applies this on every public
 * `uploadType = "ai_generated"` render.
 *
 * Technique:
 *   - ffmpeg `drawtext` filter overlays "Généré par IA — AiFlex" in the
 *     bottom-right corner of the frame, white with black outline, ~2% of
 *     the video height.
 *   - Re-encoding is H.264 veryfast + copy audio — preserves source quality
 *     reasonably, keeps CPU load low.
 *
 * Invisible provenance (C2PA) is stubbed here because the `c2patool` binary
 * isn't part of the stock Ubuntu image — install separately and swap
 * `signC2PA` to the real invocation when ready.
 */

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface WatermarkOptions {
  /** Label rendered in the overlay. Default: "Généré par IA — AiFlex". */
  label?: string;
  /** Opacity 0..1. Default: 0.72. */
  opacity?: number;
  /** ffmpeg binary path. Default: "ffmpeg" (assumes it's on PATH). */
  ffmpegBin?: string;
}

export interface WatermarkResult {
  outputPath: string;
  skipped: boolean;
  reason?: string;
}

/**
 * Apply the AI-disclosure watermark to `inputPath` and write the result to
 * `outputPath`. Returns `{ skipped: true, reason }` if ffmpeg is unavailable
 * — the caller should fall back to the un-watermarked file rather than
 * failing the whole render (compliance matters, but not at the cost of a
 * broken site — log and alert instead).
 */
export async function applyAiWatermark(
  inputPath: string,
  outputPath: string,
  options: WatermarkOptions = {}
): Promise<WatermarkResult> {
  const ffmpegBin = options.ffmpegBin || process.env.FFMPEG_BIN || "ffmpeg";
  const label = options.label || "Généré par IA — AiFlex";
  const opacity = clamp(options.opacity ?? 0.72, 0, 1);

  // Check ffmpeg availability upfront — clearer error than a spawn ENOENT
  const available = await ffmpegAvailable(ffmpegBin);
  if (!available) {
    return {
      outputPath: inputPath, // return original so caller can still upload
      skipped: true,
      reason: `ffmpeg introuvable (${ffmpegBin}). Watermark AI Act NON appliqué.`,
    };
  }

  // Build the drawtext filter:
  //   - text: escaped label
  //   - fontcolor / fontsize: white 2%-of-height with black stroke
  //   - x, y: 20px from bottom-right
  //   - alpha: opacity
  const escapedLabel = label
    .replace(/\\/g, "\\\\")
    .replace(/'/g, "\\'")
    .replace(/:/g, "\\:")
    .replace(/%/g, "\\%");

  const filter = [
    `drawtext=`,
    `text='${escapedLabel}':`,
    `fontcolor=white@${opacity.toFixed(2)}:`,
    `fontsize=(h/36):`,
    `bordercolor=black@${opacity.toFixed(2)}:`,
    `borderw=2:`,
    `x=w-text_w-24:`,
    `y=h-text_h-24`,
  ].join("");

  await fs.mkdir(path.dirname(outputPath), { recursive: true });

  const args = [
    "-y",
    "-i", inputPath,
    "-vf", filter,
    "-c:v", "libx264",
    "-preset", "veryfast",
    "-crf", "20",
    "-c:a", "copy",
    "-movflags", "+faststart",
    outputPath,
  ];

  await runSpawn(ffmpegBin, args);
  return { outputPath, skipped: false };
}

/**
 * Convenience: watermark in place via a temp file and atomically replace
 * the original. Useful when the caller doesn't want to manage two paths.
 */
export async function applyAiWatermarkInPlace(
  inputPath: string,
  options: WatermarkOptions = {}
): Promise<WatermarkResult> {
  const tmpOut = path.join(
    os.tmpdir(),
    `aiflex-wm-${Date.now()}-${path.basename(inputPath)}`
  );
  const result = await applyAiWatermark(inputPath, tmpOut, options);
  if (!result.skipped) {
    await fs.rename(tmpOut, inputPath);
    return { outputPath: inputPath, skipped: false };
  }
  // cleanup tmp if spawn ran partially
  try {
    await fs.unlink(tmpOut);
  } catch {
    /* no-op */
  }
  return result;
}

/**
 * Decide whether a project requires the AI-disclosure watermark before
 * being served publicly. Keeping this logic centralised so the rule is
 * not duplicated across routes/pipeline steps.
 */
export function requiresAiWatermark(project: {
  uploadType?: string | null;
  visibility?: string | null;
  isAdult?: boolean | null;
}): boolean {
  // User-uploaded human-shot content doesn't need our AI disclaimer.
  if (project.uploadType !== "ai_generated") return false;
  // Private circles don't broadcast — regulation targets public distribution.
  if (project.visibility !== "public") return false;
  return true;
}

// ---------------------------------------------------------------------------
// C2PA provenance (V8 §19.3) — stub
// ---------------------------------------------------------------------------

export interface C2PAMetadata {
  creatorUserId: string;
  filmId: string;
  model: string; // e.g. "seedance-2-pro-via-fal"
  generatedAt: Date;
  promptHash: string; // sha256 hex, NOT the raw prompt
}

/**
 * Sign a video file with a C2PA manifest (V8 §19.3).
 *
 * Shells out to Adobe's official `c2patool` (Rust binary, install via
 * https://github.com/contentauth/c2patool/releases). Produces an
 * embedded JUMBF manifest in the MP4 carrying the model + creator +
 * timestamp + prompt hash, verifiable on contentauthenticity.org.
 *
 * Failure modes:
 *   - Missing cert/key env vars      → returns { signed: false, reason }
 *   - c2patool binary not on PATH    → returns { signed: false, reason }
 *   - tool errors                    → returns { signed: false, reason }
 *
 * Never throws. Caller is expected to upload the source file regardless
 * (compliance + watermark visible already cover the AI-Act minimum).
 */
export async function signC2PA(
  mp4Path: string,
  metadata: C2PAMetadata
): Promise<{ signed: boolean; reason?: string }> {
  const cert = process.env.C2PA_SIGNING_CERT_PATH;
  const key = process.env.C2PA_SIGNING_KEY_PATH;
  const bin = process.env.C2PA_TOOL_BIN || "c2patool";

  if (!cert || !key) {
    return {
      signed: false,
      reason:
        "C2PA_SIGNING_CERT_PATH / C2PA_SIGNING_KEY_PATH not set — provenance signature skipped.",
    };
  }

  // Build the C2PA claim — minimal AI-generated assertion + author + soft
  // binding to the model. Spec : https://c2pa.org/specifications/
  const claim = {
    title: `AIflex film ${metadata.filmId}`,
    format: "video/mp4",
    claim_generator: `AIflex/1.0 ${metadata.model}`,
    claim_generator_info: [
      { name: "AIflex", version: "1.0" },
    ],
    assertions: [
      {
        label: "c2pa.actions",
        data: {
          actions: [
            {
              action: "c2pa.created",
              when: metadata.generatedAt.toISOString(),
              softwareAgent: metadata.model,
              digitalSourceType: "trainedAlgorithmicMedia",
            },
          ],
        },
      },
      {
        label: "c2pa.creative_work",
        data: {
          "@context": "https://schema.org/",
          "@type": "CreativeWork",
          author: [{ "@type": "Person", identifier: metadata.creatorUserId }],
        },
      },
      {
        label: "ai.aiflex.prompt-hash",
        data: { sha256: metadata.promptHash },
      },
    ],
  };

  const claimPath = path.join(
    os.tmpdir(),
    `aiflex-c2pa-${metadata.filmId}-${Date.now()}.json`
  );
  await fs.writeFile(claimPath, JSON.stringify(claim, null, 2));

  try {
    const args = [
      mp4Path,
      "--manifest",
      claimPath,
      "--signer-cert",
      cert,
      "--private-key",
      key,
      "--force",
      "--output",
      mp4Path,
    ];
    await runSpawn(bin, args, { silent: true });
    return { signed: true };
  } catch (err) {
    return {
      signed: false,
      reason: err instanceof Error ? err.message : "c2patool failed",
    };
  } finally {
    fs.unlink(claimPath).catch(() => {});
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function ffmpegAvailable(bin: string): Promise<boolean> {
  try {
    await runSpawn(bin, ["-version"], { silent: true });
    return true;
  } catch {
    return false;
  }
}

function clamp(n: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, n));
}

function runSpawn(
  bin: string,
  args: string[],
  opts: { silent?: boolean } = {}
): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn(bin, args, {
      stdio: opts.silent ? "ignore" : ["ignore", "pipe", "pipe"],
    });
    let stderr = "";
    if (!opts.silent) {
      child.stderr?.on("data", (buf) => {
        stderr += buf.toString();
      });
    }
    child.on("error", reject);
    child.on("exit", (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(
          new Error(
            `${bin} exited with code ${code}${stderr ? `: ${stderr.slice(-500)}` : ""}`
          )
        );
      }
    });
  });
}
